### ISSUE TITLE
RAILS_ROOT not defined

### ISSUE THREAD

**Issue by grimen** [redinger/validation_reflection#1]
When running isolated tests on Rails plugin outside of a Rails project ValidationReflection fails because it can't find any constant definition for RAILS_ROOT. It's a good practice not to require such if it's not completely necessary - most cases not, and in this case it works fine just setting it to whatever to just sloppy-define it, or skip the expression if it's not defined.

**Comment by redinger** [comment]
Thanks for the commit! Merged.

**Comment by halo** [comment]
On Rails 3.0.0 beta2 I'm getting the following deprecation warning:

DEPRECATION WARNING: RAILS_ROOT is deprecated! Use Rails.root instead. (called from join at /Library/Ruby/Gems/1.8/gems/validation_reflection-0.3.6/lib/validation_reflection.rb:36)
