### ISSUE TITLE
Yikes - breaks model.reload!

### ISSUE THREAD

**Issue by inspire22** [redinger/validation_reflection#8]
class User < ActiveRecord::Base
  validates_uniqueness_of :email, :message => "is already in use on an account.  Please use one email per account"
end

u=User.first
u.reload

-> ArgumentError: wrong number of arguments (0 for 1)
method reload   in testing.rb at line 40

**Comment by redinger** [comment]
Fixed in 0.3.8 & 1.0.0.rc.1

**Comment by inspire22** [comment]
Thanks!

It looks like AR3 has built in support for validation reflections?  What are the differences?
